# -*- coding: utf-8 -*-
"""task7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VfUnqEYh3fmEcOt4pyH0g6SufVjJnD5o
"""

import sqlite3

conn = sqlite3.connect("sales_data.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS sales (
    id INTEGER PRIMARY KEY,
    product TEXT,
    quantity INTEGER,
    price REAL
)
""")

sample_data = [
    ("Apple", 10, 2.5),
    ("Banana", 5, 1.2),
    ("Orange", 8, 1.5),
    ("Apple", 4, 2.5),
    ("Banana", 9, 1.2)
]
cursor.executemany("INSERT INTO sales (product, quantity, price) VALUES (?, ?, ?)", sample_data)

conn.commit()
conn.close()

import sqlite3
import pandas as pd

conn = sqlite3.connect("sales_data.db")

query = """
SELECT product, SUM(quantity) AS total_qty, SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
"""

df = pd.read_sql_query(query, conn)
conn.close()

print(df)

import matplotlib.pyplot as plt

df.plot(kind='bar', x='product', y='revenue')
plt.title("Revenue by Product")
plt.xlabel("Product")
plt.ylabel("Revenue")
plt.tight_layout()
plt.show()